# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.SmallIntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('c_email', models.EmailField(max_length=254, verbose_name='Confirmar e-mail')),
                ('tyc', models.BooleanField(verbose_name='Terminos y condiciones')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.CharField(max_length=3)),
                ('sillas', models.SmallIntegerField()),
                ('cubresillas', models.SmallIntegerField(null=True)),
                ('mesas', models.SmallIntegerField()),
                ('manteles', models.SmallIntegerField()),
                ('cubremanteles', models.SmallIntegerField()),
                ('juego_loza', models.SmallIntegerField(verbose_name='Juegos de loza, vaso, plato, cubiertos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paquete')),
            ],
        ),
    ]
