# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(default='Casa', max_length=20),
            preserve_default=False,
        ),
    ]
