# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='fecha_ahora',
            field=models.DateField(default='2016-05-16'),
        ),
    ]
