# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paquete_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='cubresillas',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='cubre sillas'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='juego_loza',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Juegos de loza, vaso, plato, cubiertos'),
        ),
    ]
