# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservacion_fecha_ahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='confirmacion',
            field=models.BooleanField(default=False),
        ),
    ]
