# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160621_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
