# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reservacion_confirmacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_ahora',
            field=models.DateField(auto_now_add=True),
        ),
    ]
