# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160702_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='confirmacion',
            field=models.BooleanField(),
        ),
    ]
