# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160621_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
